### PR TITLE
Custom resources & rest gem

### PR DESCRIPTION
**Pull request by damacus**
Hi!

I've been speaking to @robcoward about moving this cookbook to use custom resources & the [Opsview rest gem](https://github.com/cparedes/opsview_rest) (which I'm in the process of updating too). 

I've started off by moving things into their own custom resource, but I've really like some feedback before I do any more work!

### CODE REVIEW

**Comment by damacus** [comment]
hi! 

Is this still maintained?

**Comment by chrisgit** [comment]
Hi @damacus 

We have had no need to make any changes to this cookbook and internally use a wrapper cookbook which does much of what we require. However I have spoken to a few people in the business to see where we are with this cookbook and if we have any short to medium term plans.

We will get back to you shortly with a better response.

**Comment by damacus** [comment]
Thanks, I was trying to use it with a previous client, and needed the updated Ruby Gem (which I can't get released either!).

Chef have a partener cookbook program kicking around which might be worth looking at. 
https://blog.chef.io/2016/02/23/chef-launches-partner-cookbook-program-to-expand-devops-ready-technology-ecosystem/

https://www.chef.io/partners/cookbooks/

**Comment by damacus** [comment]
@chrisgit thanks for the response. 

If your cookbook is purely internal. Would it be possible to remove it from the Chef Supermarket as in its current state it isn't working for anyone else. Which is kind of the point of the supermarket :/

**Comment by chrisgit** [comment]
Updated the repo status

**Comment by damacus** [comment]
Thanks @chrisgit 

I'll be in contact (probably from sous-chefs)!

**Pull request closed without merging**
